/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ffmpeg_codec_VideoCodec */

#ifndef _Included_com_example_ffmpeg_codec_VideoCodec
#define _Included_com_example_ffmpeg_codec_VideoCodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ffmpeg_codec_VideoCodec
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ffmpeg_1codec_VideoCodec_decode
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
